#!/bin/sh

set -e

if [ ! -d ssl ]; then
    mkdir ssl
fi

# Create the root CA (Certificate Authority)
openssl ecparam -genkey -name prime256v1 -out ssl/dockerwatch-ca.key

## Certificate signing request for root CA
openssl req -x509 -new -SHA256 -nodes -key ssl/dockerwatch-ca.key -days 3650 -subj "/C=SE/" -out ssl/dockerwatch-ca.pem

# Create the server certificate
openssl ecparam -genkey -name prime256v1 -out ssl/dockerwatch-server.key

## Certificate signing request for server certificate
openssl req -new -SHA256 -key ssl/dockerwatch-server.key -subj "/C=SE/CN=localhost/" -nodes -out ssl/dockerwatch-server.csr

## Sign the server certificate using the root CA
openssl x509 -req -SHA256 -days 365 -in ssl/dockerwatch-server.csr -CA ssl/dockerwatch-ca.pem -CAkey ssl/dockerwatch-ca.key -CAcreateserial -out ssl/dockerwatch-server.pem
